Jax -> Pytorch
ejnnr/cupbearer pull request #14
Opened 2023-10-30 22:56 UTC by ejnnr

Very early stage draft, a lot of stuff hasn't been ported yet and straight up doesn't work. Things that should more or less work:
* Training and evaluating classifiers
* Backdoor data
* Mahalanobis training and eval
But even for these there are caveats, e.g. GPT-4 did a lot of the pytorch version of WaNet and I haven't tested that yet, and I also haven't merged in the more recent changes to validation data and the fix in #13 

I'm planning to finish porting stuff, which mainly affects abstractions and adversarial examples, clean up things that are unneeded now, and test things more extensively. I won't have much time Tue/Wed, but hopefully I'll make decent progress on those things in the second half of this week. In the meantime, hopefully this gives you a sense of what things will change @VRehnberg to avoid doing unnecessary work. (I think your recent changes will hopefully be pretty feasible to merge)

2023-10-31 09:28 UTC, VRehnberg commented
On Wanet the original implementation uses grid_sample instead of interpolate. Difference is probably about as big we had before so I believe that is fine. Here is my investigation from before when comparing them:
https://stackoverflow.com/questions/76961133/differences-between-cubic-2d-interpolation-methods-in-scipy-and-pytorch

2023-10-31 09:37 UTC, VRehnberg commented
Looks promising, let me know if you want any help or when you want a proper review.

2023-11-03 05:35 UTC, ejnnr commented
The mahalanobis detector wasn't actually working yet, I just didn't notice because one of the tests wasn't running. Fixed now, and abstractions should also work. I think the main missing pieces are:
- [ ] Porting adversarial examples (maybe now that we're using pytorch, we should use an existing library for that)
- [ ] Porting the robust optimization version of abstractions (or maybe just rip it out for now until we actually want to use it again)
- [ ] Merge in the improvements from `main`
- [ ] Ideally add some more automated tests
- [ ] Check WaNet implementation
- [ ] Check that detectors still perform similarly
- [ ] Clean-up (e.g. remove `Trainer` class)

2023-11-03 13:15 UTC, VRehnberg commented
> Porting adversarial examples (maybe now that we're using pytorch, we should use an existing library for that)

I've seen two existing implementation while looking for defense methods [torchattack](https://github.com/Harry24k/adversarial-attacks-pytorch) and [DeepRobust](https://github.com/Harry24k/adversarial-attacks-pytorch). Haven't looked in any detail, but torchattack seems a bit better maintained.

2023-11-04 02:23 UTC, ejnnr commented
I merged things now, but the backdoor tests are failing, I'll probably fix that next week.

For WaNet, I'm currently using `upsample` and `grid_sample` like in the original implementation, which also lead to other changes (like warping fields having values in [-1, 1] instead of [0, size]).

2023-11-06 07:04 UTC, VRehnberg commented
> I merged things now, but the backdoor tests are failing, I'll probably fix that next week.
> 
> For WaNet, I'm currently using `upsample` and `grid_sample` like in the original implementation, which also lead to other changes (like warping fields having values in [-1, 1] instead of [0, size]).

Great. I remember scaling everything correctly was a tricky part. But, in this case it's probably easier just to try to replicate the original implementation. There's an extra factor 0.5 in the control_grid that should be removed as well now if I remember correctly, but I'll make sure to go over this part in extra detail when reviewing.

2023-11-15 01:03 UTC, ejnnr commented
I think this is good enough to review now. My main concern is whether the methods actually work correctly (abstractions seem to perform a bit worse than in the Jax implementation). But they do at least seem to work at all, and there's a priori no strong reason to think the jax version was *more* correct than this one.

2023-11-15 01:42 UTC, ejnnr commented
Main design uncertainties:
- How should we extract activations from models? The main alternative to the current `HookedModel` approach would be just using pytorch forward hooks on every submodule in a network. Gives somewhat less control to people implementing new models, but less overhead.
- Relatedly, how should we configure which activations to actually use? (the `names` argument in various places) I think right now this basically isn't configurable at all and just uses everything, which is pretty silly (except for abstraction, where there's a reasonable default). We could make each model automatically provide defaults. For configuration, we should probably let users specify the path to a function that will compute the names to use (statically encoding these is cumbersome if model sizes can change)

2023-11-15 10:54 UTC, VRehnberg requested changes
Looking good, couldn't see any problem in Wanet implementation. Only found some few things overall that had yet to be updated.

Edit: Oh, and there are a gazillion warnings from lightning but, I'm not sure there's anything we can do about most of them.

2023-11-15 10:54 UTC, VRehnberg commented on src/cupbearer/data/backdoors.py
> +        field = F.upsample(
```suggestion
        field = F.interpolate(
```
upsample has become deprecated, but should just be a straight replacement with interpolate

2023-11-15 10:54 UTC, VRehnberg commented on src/cupbearer/scripts/eval_classifier.py
> +        cfg.dir.path / "model.ckpt", test_loader_names=["test"]
```suggestion
        cfg.dir.path / "last.ckpt", test_loader_names=["test"]
```
This should be last, no?

2023-11-15 11:16 UTC, VRehnberg commented
> Main design uncertainties:
> 
>     * How should we extract activations from models? The main alternative to the current `HookedModel` approach would be just using pytorch forward hooks on every submodule in a network. Gives somewhat less control to people implementing new models, but less overhead.
> 
>     * Relatedly, how should we configure which activations to actually use? (the `names` argument in various places) I think right now this basically isn't configurable at all and just uses everything, which is pretty silly (except for abstraction, where there's a reasonable default). We could make each model automatically provide defaults. For configuration, we should probably let users specify the path to a function that will compute the names to use (statically encoding these is cumbersome if model sizes can change)

It's ok for now so I think this can go into a separate PR.

 * How to extract activations?
     * Flexibility is good in the sense that ideally you should be able to use almost any subset of layers to capture activations from.
         * Though if this is done you have to be careful of memory requirements for large models. We only want to store activations from layers we're actually using right now.
         * Also, if it is this general then you might want a helper for picking these activations and storing that as a config.
     * There are a few detectors where we might want to do interventions on the activations.
          * This isn't possible with the current implementation?
     * I think forward hooks might be the way to go in the future. However,
         * there will be some work needed before it is as useful as HookedModels are now.
 * How to choose activations to use?
     * Reasonable defaults for at least implemented models
         * If we add support for using any model, then I think it is better to make choice of activations explicit for generic models.
     * A way to choose which activations to use. Pointing to a function is general enough.

2023-11-16 06:32 UTC, ejnnr commented on pyproject.toml
>      "flax~=0.7.0",
Yep, thanks!

2023-11-16 06:38 UTC, ejnnr commented
Notes to self:

- [ ] Fix or hide spurious warnings (at least the ones I get on my machine)
- [ ] Force models to have a method that generates default names for activations
- [ ] (optional, could also push this to another PR) Make names configurable by passing a function to scripts (or a string that's a path to a function for CLI compatibility)

After that should be fine to merge.

We'll probably switch to pytorch forward hooks, but in a separate PR.

2023-11-16 13:44 UTC, VRehnberg commented
> Notes to self:
> 
>     * [ ]  Fix or hide spurious warnings (at least the ones I get on my machine)

Here are a (filtered) list of the type of warnings I see.

```
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning_utilities/core/imports.py:13: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/fabric/__init__.py:40: Deprecated call to `pkg_resources.declare_namespace('lightning.fabric')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages

  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/torchmetrics/utilities/imports.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _PYTHON_LOWER_3_8 = LooseVersion(_PYTHON_VERSION) < LooseVersion("3.8")

tests/test_data.py::test_backdoor_relabeling[WanetBackdoor]
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
    return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

tests/test_pipeline.py::test_eval_classifier
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if not hasattr(tensorboard, "__version__") or LooseVersion(

tests/test_pipeline.py::test_eval_classifier
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:634: Checkpoint directory /tmp/pytest-of-vikren/pytest-18/tests_test_pipeline_py0 exists and is not empty.

tests/test_pipeline.py::test_eval_classifier
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/pytorch/utilities/data.py:104: Total length of `list` across ranks is zero. Please make sure this was your intention.

  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py:293: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

tests/test_pipeline.py::test_finetuning_detector
  /home/vikren/miniconda3/envs/cupbearer-tmp/lib/python3.10/site-packages/lightning/pytorch/trainer/configuration_validator.py:74: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
```

2023-11-16 13:48 UTC, VRehnberg approved these changes

2023-11-17 04:35 UTC, ejnnr commented
Haven't fixed *all* the warnings yet and several new open TODOs, but want to merge this for now since we're already building on this and this PR is too big as it is.

Note on abstractions: the reason they don't work quite as well might be that I deliberately made the abstract steps completely linear, removing the ReLU, because I'd been meaning to try that for a while (just forgot about that change). When we investigate abstractions more seriously, we should benchmark this in realistic cases.

2023-11-17 04:35 UTC, merged