Make tasks more flexible
ejnnr/cupbearer pull request #29
Opened 2024-02-29 01:40 UTC by ejnnr

Mainly, we'd like to allow detectors that require both trusted and untrusted data (where untrusted data is an unlabeled mix of clean and anomalous data). I ended up making a bunch of other small changes that seemed good while I was doing this:
- Removed `TaskConfigBase`, it was pretty pointless
- Added a `get_test_split()` method to `DatasetConfig`---this will sometimes raise NotImplementedError but for existing datasets we can always make it work, and it's useful when defining tasks. I don't really like the design though, maybe we should just explicitly have "dataset pair" objects?
- Modified adversarial examples a bit to provide test splits
- Replaced the `RemoveLabelMixDataset` with an argument to `TestDataMix` (now `MixedData` since it's not just used for tests). Probably simpler this way

Demo notebook and tests pass but I didn't add new ones to actually test all the mixing logic etc. is correct, just did some manual sanity checks.

@VRehnberg Let me know if you have objections to the design or better ideas for what it should look like, otherwise we can merge this.

2024-02-29 04:39 UTC, ejnnr commented
Hm, I should definitely let the trusted and untrusted clean training data be different before merging, otherwise it's way too easy.

2024-02-29 16:02 UTC, VRehnberg approved these changes
LGTM, though haven't run the test-suite yet but feel to merge if you've made sure the test-suite runs for you.

2024-02-29 16:02 UTC, VRehnberg commented on src/cupbearer/tasks/_config.py
> +        # We split the training data up into three parts:
I suppose splitting this way is more realistic in a sense.

2024-03-01 07:37 UTC, VRehnberg commented
I've found some things so hold off on merging.

2024-03-01 08:27 UTC, VRehnberg requested changes
Found some things as I was running the test suite. Might be things beyond these as well, but as #30 might supercede this PR I left it at these.

2024-03-01 08:27 UTC, VRehnberg commented on src/cupbearer/tasks/adversarial_examples.py
> +    def _get_anomalous_data(self, train: bool) -> DatasetConfig:
```suggestion
    def _get_anomalous_data(self) -> DatasetConfig:
        return self._get_anomalous_data_by_split(train=True)

    def _get_anomalous_test_data(self) -> DatasetConfig:
        return self._get_anomalous_data_by_split(train=False)

    def _get_anomalous_data_by_split(self, train: bool) -> DatasetConfig:
```
Something like this to match signature in parent class.

2024-03-01 08:27 UTC, VRehnberg commented on tests/test_pipeline.py
>              backdoor=data.CornerPixelBackdoor(),
```suggestion
```
Backdoor is no longer an argument to tasks. This is the same for all the below tests as well.

2024-03-01 08:27 UTC, VRehnberg commented on src/cupbearer/tasks/backdoor_detection.py
> +        self._backdoor = backdoor_data.backdoor
The name change from `backdoor` to `_backdoor` breaks the `test_wanet` test. The test should be updated.

2024-03-03 02:36 UTC, ejnnr commented
Closing this in favor of #30 (I think the changes there are good overall and even if we iterate on them a bit, we won't go back to this version)

2024-03-03 02:36 UTC, closed without merging